name: easyfood_app
description: EasyFood App.

version: 2.3.3+61
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  provider: ^6.0.5
  get_it: ^7.6.4
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  uuid: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  visibility_detector: ^0.4.0+2
  dio_cache_interceptor: ^3.5.0
  crypto: ^3.0.3
  logger: ^2.0.2+1
  equatable: ^2.0.5
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.0.0
  permission_handler: ^11.2.0
  string_validator: ^1.0.2
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_performance: ^0.10.0+4
  package_info_plus: ^8.0.0
  qr_flutter: ^4.1.0
  flutter_animate: ^4.5.0
  brasil_fields: ^1.14.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  modal_progress_hud_nsn: ^0.5.1
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/