// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKY1l-HgRnyPwF4sq-SFZs19Wn7s4Rs1w',
    appId: '1:229321383071:web:e82a52ff0c2a3e182d96aa',
    messagingSenderId: '229321383071',
    projectId: 'easyfood-app-flutter',
    authDomain: 'easyfood-app-flutter.firebaseapp.com',
    storageBucket: 'easyfood-app-flutter.appspot.com',
    measurementId: 'G-T3CESHW31Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwaUsmhtYmgWTLBeCCoHHlKs8A9iATLao',
    appId: '1:229321383071:android:b7d42a008cce28a42d96aa',
    messagingSenderId: '229321383071',
    projectId: 'easyfood-app-flutter',
    storageBucket: 'easyfood-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpXuJ5YXRwHWN4ksvTM1qXaZzf4MJTByg',
    appId: '1:229321383071:ios:a8c39205a3fb84902d96aa',
    messagingSenderId: '229321383071',
    projectId: 'easyfood-app-flutter',
    storageBucket: 'easyfood-app-flutter.appspot.com',
    iosBundleId: 'br.com.stirr.easyfood.app.easyfoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpXuJ5YXRwHWN4ksvTM1qXaZzf4MJTByg',
    appId: '1:229321383071:ios:a8c39205a3fb84902d96aa',
    messagingSenderId: '229321383071',
    projectId: 'easyfood-app-flutter',
    storageBucket: 'easyfood-app-flutter.appspot.com',
    iosBundleId: 'br.com.stirr.easyfood.app.easyfoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKY1l-HgRnyPwF4sq-SFZs19Wn7s4Rs1w',
    appId: '1:229321383071:web:b2fdee4cf86801132d96aa',
    messagingSenderId: '229321383071',
    projectId: 'easyfood-app-flutter',
    authDomain: 'easyfood-app-flutter.firebaseapp.com',
    storageBucket: 'easyfood-app-flutter.appspot.com',
    measurementId: 'G-71TSMFED2T',
  );

}